#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
   
    min_num = min(arr)
    max_num = max(arr)
    sum_arr = sum(arr)
    sum_max = sum_arr - min_num
    sum_min = sum_arr - max_num
    print("{} {}".format(sum_min ,sum_max))

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
